add health / refresh dependency
langgenius/dify-sandbox pull request #34
Opened 2024-08-12 16:25 UTC by luckylhb90

2024-08-13 05:06 UTC, Yeuoly requested changes

2024-08-13 05:06 UTC, Yeuoly commented on internal/controller/router.go
> +		// 健康监测
pls use English instead.

2024-08-13 06:37 UTC, luckylhb90 commented on internal/controller/router.go
> +		// 健康监测
fixed

2024-08-13 07:30 UTC, luckylhb90 commented
solved #22

2024-08-19 07:39 UTC, Yeuoly approved these changes
LGTM

2024-08-19 07:47 UTC, merged